apiVersion: v1
kind: Service
metadata:
  name: inference-service
spec:
  type: NodePort  # Add this line
  selector:
    app: inference
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080  # You can choose a port between 30000-32767

